---
- name: Copy
  hosts: apache
  sudo: yes
  tasks:
    - name: example copying file with owner and permissions
      copy:
        src: /home/jenkins/jenkins_slave/workspace/Buildtest/index.html
        dest: /var/lib/tomcat8/webapps/ROOT/index.html
        owner: ansible
